### ISSUE TITLE
New oobabooga update breaks your awesome extension, here is how to fix it.

### ISSUE THREAD

**Issue by RandomInternetPreson** [wsippel/bark_tts#18]
Hello, I really like your extension.

Oobabooga updated the code and your extension no longer works:

https://old.reddit.com/r/oobaboogazz/comments/14q3v2y/news_added_sessions_basic_multiuser_support/jqo7xgn/

Looking at your script.py file on line 165 
 f'extensions/bark_tts/outputs/{shared.character}_{int(time.time())}.wav')
 
 if you change it to look like this: 
             f'extensions/bark_tts/outputs/_{int(time.time())}.wav')

the extension will work again.  Oobabooga removed the character and history shared variables.

**Comment by wsippel** [comment]
Thanks for the heads up and the PR, though it turns out the upstream changes were a bit more comprehensive, so I couldn't use your patch in the end. The chat history handling changed as well, and the character name is still available, it just has to be accessed differently now. Hope I fixed everything, feel free to give it a spin. Still, thanks for going through the effort and posting a PR, it's very much appreciated! :+1:
